language: android
jdk: oraclejdk8
sudo: false

before_install:
 - chmod +x gradlew

notifications:
  email:
    recipients:
    - thedmx74@hotmail.fr
    on_success: always # default: change
    on_failure: always # default: always

android:
  components:
    - build-tools-28.0.3
    - android-28
    - android-19
    - sys-img-armeabi-v7a-android-19

script:
- ./gradlew build test connectedCheck

before_script:
  # Create and start emulator, android 19 minimum supported
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
